import Head from "next/head";
import { useState } from "react";
import Map from "@/components/Map/Map";
import SearchPlaces from "@/components/SearchPlaces/SearchPlaces";

// Change Token before git push!!!
const accessToken =
  "pk.eyJ1Ijoia2V0bmVrIiwiYSI6ImNsaDVybDl5azA0ZzYzZ21wcmJvZnlxeGYifQ.7xOZhYeVEcLNK833qEUjUw";

export default function Home() {
  const [lng, setLng] = useState(10.000654);
  const [lat, setLat] = useState(53.550341);
  const [zoom, setZoom] = useState(9);
  const [center, setCenter] = useState(null);

  const getNewDestination = async (url) => {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        console.error("Loading new destination went wrong!");
      }
      const data = await response.json();
      setCenter(data?.features[0]?.center);
    } catch (error) {
      console.error(error);
    }
  };

  const handleSearchSubmit = (event) => {
    event.preventDefault();
    const form = event.target;

    const inputValue = form.search.value;
    getNewDestination(
      `https://api.mapbox.com/geocoding/v5/mapbox.places/${inputValue}.json?access_token=${accessToken}`
    );
  };

  return (
    <>
      <Head>
        <title>Bicycle</title>
        <meta charset="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Map
          accessToken={accessToken}
          lng={lng}
          lat={lat}
          zoom={zoom}
          center={center}
        />
        <SearchPlaces onSearchSubmit={handleSearchSubmit} />
      </main>
    </>
  );
}
