import Head from "next/head";
import MapLogic from "@/components/MapLogic/MapLogic";

export default function Home({ accessToken, mapStyle }) {
  return (
    <>
      <Head>
        <title>Bicycle</title>
        <meta charset="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MapLogic accessToken={accessToken} mapStyle={mapStyle} />
    </>
  );
}
